// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NewYeomanProject
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string newTempProjectCommandPackageString = "76f7bc2c-3947-47dc-a6c5-e030e98eeed6";
        public const string startPageExtenderPackageString = "c2da0fbd-86a2-434a-b830-22c362cceb4b";
        public const string startPageToolWindowString = "387cb18d-6153-4156-9257-9ac3f9207bbe";
        public const string guidNewTempProjectCommandPackageCmdSetString = "8570b726-5877-4583-8764-5c9d7c945ea7";
        public const string guidImagesString = "dbb0b277-359d-445e-89a7-ff09f806ca18";
        public static Guid newTempProjectCommandPackage = new Guid(newTempProjectCommandPackageString);
        public static Guid startPageExtenderPackage = new Guid(startPageExtenderPackageString);
        public static Guid startPageToolWindow = new Guid(startPageToolWindowString);
        public static Guid guidNewTempProjectCommandPackageCmdSet = new Guid(guidNewTempProjectCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NewTempProjectCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
