// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NewYeomanProjectVsix
{
    static class Vsix
    {
        public const string Id = "4B89A6EA-E334-4719-B41D-8B1894C56039";
        public const string Name = "New Yeoman Project";
        public const string Description = @"Adds `File > New > Yeoman Project...` command to create a new Yeoman scaffoled project.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Greg Trevellick";
        public const string Tags = "Yeoman; scaffold; New project; Project; Yo; Generator; Generators;";
    }
}
